import {createHmac,randomInt,timingSafeEqual,randomBytes} from 'node:crypto';
export class Problem extends Error{constructor(message,status=400){super(message);this.status=status;}}
export const normalize=(factor,value)=>factor==='email'?String(value||'').trim().toLowerCase():String(value||'').replace(/[\s()-]/g,'');
export function validateContact(factor,value){if(!['email','whatsapp'].includes(factor))throw new Problem('Unsupported verification factor.');value=normalize(factor,value);if(value.length>254||(factor==='email'?!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value):!/^\+[1-9]\d{7,14}$/.test(value)))throw new Problem('Enter a valid '+(factor==='email'?'email address.':'WhatsApp number with its country code.'));return value;}
export const code=()=>String(randomInt(100000,1000000));
export const token=()=>randomBytes(32).toString('base64url');
export const digest=(secret,text)=>createHmac('sha256',secret).update(text).digest('hex');
export function compare(a,b){return typeof a==='string'&&typeof b==='string'&&a.length===b.length&&timingSafeEqual(Buffer.from(a),Buffer.from(b));}
export function verifyChallenge(challenge,{value,code},secret,now=Date.now()){if(!challenge||challenge.used||challenge.expires<now||challenge.attempts>=5)throw new Problem('Code expired or too many attempts. Request a new code.');challenge.attempts++;if(challenge.value!==value||!compare(challenge.hash,digest(secret,challenge.value+':'+code)))throw new Problem('That code does not match. Please try again.');challenge.used=true;return challenge.value;}
export function validateApplication(body,session){const name=String(body.name||'').trim();if(name.length<2||name.length>100)throw new Problem('Provide your name as printed in the book.');if(!['green','blue'].includes(body.book))throw new Problem('Choose a Green Book or Blue Book.');if(body.consent!==true||body.consentVersion!=='2026-10-07')throw new Problem('Consent to document review and status messages is required.');const email=validateContact('email',body.email),whatsapp=validateContact('whatsapp',body.whatsapp);if(session.verified?.email!==email||session.verified?.whatsapp!==whatsapp)throw new Problem('Verify both contacts before submitting.',403);if(typeof body.photo!=='string'||!/^data:image\/jpeg;base64,[A-Za-z0-9+/]+=*$/.test(body.photo))throw new Problem('Provide a JPEG document photo.');const photo=Buffer.from(body.photo.split(',')[1],'base64');if(photo.length<100||photo.length>3*1024*1024||photo[0]!==255||photo[1]!==216||photo.at(-2)!==255||photo.at(-1)!==217)throw new Problem('Provide a valid JPEG photo smaller than 3 MB.');return {name,email,whatsapp,book:body.book,photo,consentVersion:body.consentVersion};}
export function validateDecision(current,status){if(!['accepted','declined'].includes(status))throw new Problem('Decision must be accepted or declined.');if(current!==status&&current!=='pending')throw new Problem('This application already has a final decision.',409);return current!==status;}
export function spreadsheetText(value){const text=String(value??'');return /^[=+\-@\t\r]/.test(text)?"'"+text:text;}
