import {createSign} from 'node:crypto';
import {readFile} from 'node:fs/promises';
import {spreadsheetText} from './core.mjs';
export const columns=['Reference','CreatedAt','Name','Email','WhatsApp','Book','PhotoURL','Status','ReviewedBy','ReviewedAt','ReviewNote','PasskeyCredentialId','PasskeyPublicKey','PasskeyCounter','PasskeyPRFSupported','ConsentVersion','RegistrationMessage','DecisionMessage','BookFrontURL','BookBackURL','ChallengePhotoURL','VideoURL','ChallengeCode','PassportCountry','PassportVerified'];
export class GoogleStore{
 constructor(env){this.env=env;this.cached=null;}
 async access(){if(this.cached?.expires>Date.now()+60000)return this.cached.token;const credential=JSON.parse(await readFile(this.env.GOOGLE_APPLICATION_CREDENTIALS,'utf8'));const now=Math.floor(Date.now()/1000);const head=Buffer.from(JSON.stringify({alg:'RS256',typ:'JWT'})).toString('base64url');const claims=Buffer.from(JSON.stringify({iss:credential.client_email,scope:'https://www.googleapis.com/auth/drive https://www.googleapis.com/auth/spreadsheets',aud:'https://oauth2.googleapis.com/token',iat:now,exp:now+3600})).toString('base64url');const input=head+'.'+claims;const sig=createSign('RSA-SHA256').update(input).sign(credential.private_key,'base64url');const response=await fetch('https://oauth2.googleapis.com/token',{method:'POST',body:new URLSearchParams({grant_type:'urn:ietf:params:oauth:grant-type:jwt-bearer',assertion:input+'.'+sig}),signal:AbortSignal.timeout(20000)});if(!response.ok)throw new Error('Google authentication failed.');const data=await response.json();this.cached={token:data.access_token,expires:Date.now()+data.expires_in*1000};return data.access_token;}
 async request(url,options={}){const res=await fetch(url,{...options,headers:{Authorization:'Bearer '+await this.access(),...options.headers},signal:AbortSignal.timeout(30000)});if(!res.ok)throw new Error('Google storage request failed ('+res.status+').');return res.status===204?null:res.json();}
 async photo(reference,buffer){return this.media(reference,buffer,'image/jpeg');}
 async media(reference,buffer,type){const query="'"+this.env.GOOGLE_DRIVE_FOLDER_ID+"' in parents and trashed = false and appProperties has { key='newTibetReference' and value='"+reference+"' }";const existing=await this.request('https://www.googleapis.com/drive/v3/files?includeItemsFromAllDrives=true&supportsAllDrives=true&q='+encodeURIComponent(query)+'&fields=files(id)');if(existing.files?.length){const id=existing.files[0].id;return {id,url:'https://drive.google.com/file/d/'+id+'/view'};}const boundary='new-tibet-'+reference.slice(-48);const meta={name:reference+(type==='image/jpeg'?'.jpg':type==='video/webm'?'.webm':'.mp4'),parents:[this.env.GOOGLE_DRIVE_FOLDER_ID],appProperties:{newTibetReference:reference}};const body=Buffer.concat([Buffer.from('--'+boundary+'\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n'+JSON.stringify(meta)+'\r\n--'+boundary+'\r\nContent-Type: '+type+'\r\n\r\n'),buffer,Buffer.from('\r\n--'+boundary+'--')]);const file=await this.request('https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&supportsAllDrives=true&fields=id',{method:'POST',headers:{'Content-Type':'multipart/related; boundary='+boundary},body});return {id:file.id,url:'https://drive.google.com/file/d/'+file.id+'/view'};}
 async removePhoto(id){await this.request('https://www.googleapis.com/drive/v3/files/'+encodeURIComponent(id)+'?supportsAllDrives=true',{method:'DELETE'});}
 sheet(range,method,body){return this.request('https://sheets.googleapis.com/v4/spreadsheets/'+this.env.GOOGLE_SHEET_ID+'/values/'+encodeURIComponent("'Applications'!"+range)+(method==='POST'?':append?valueInputOption=RAW&insertDataOption=INSERT_ROWS':method==='PUT'?'?valueInputOption=RAW':''),{method,...(body?{headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})});}
 async initialize(){await this.sheet('A1:Y1','PUT',{values:[columns]});}
 async append(app){const existing=await this.sheet('A:A','GET');if(existing.values?.some(row=>row[0]===app.reference))return;const key=app.passkey||{};return this.sheet('A:Y','POST',{values:[[app.reference,app.createdAt,spreadsheetText(app.name),app.email,app.whatsapp,app.book,app.photoURL,app.status,'','','',key.id||'',key.publicKey||'',key.counter||0,key.prfSupported||false,app.consentVersion,'queued','',app.media?.front?.url||'',app.media?.back?.url||'',app.media?.challenge?.url||'',app.media?.video?.url||'',app.challengeCode||'',app.passport?.country||'',app.passport?.verified||false]]});}
 async update(app){const data=await this.sheet('A:A','GET');const index=data.values?.findIndex(row=>row[0]===app.reference);if(index===undefined||index<1)throw new Error('Application row missing.');const row=index+1;await this.sheet('H'+row+':J'+row,'PUT',{values:[[app.status,app.reviewedBy||'',app.reviewedAt||'']]});if(app.reviewNote!==undefined)await this.sheet('K'+row,'PUT',{values:[[spreadsheetText(app.reviewNote)]]});await this.sheet('Q'+row+':R'+row,'PUT',{values:[[app.registrationMessage||'queued',app.decisionMessage||'']]});}
}
