import http from 'node:http';
import {DatabaseSync} from 'node:sqlite';
import {mkdirSync,readFileSync,existsSync} from 'node:fs';
import {resolve,extname} from 'node:path';
import {pathToFileURL} from 'node:url';
import {randomUUID} from 'node:crypto';
import {Problem,token,digest,compare,code,validateContact,verifyChallenge,validateApplication,validateDecision} from './core.mjs';
import {GoogleStore} from './google.mjs';
import {Messages} from './messages.mjs';
const required=['SESSION_SECRET','FRONTEND_ORIGIN','RP_ID','REVIEW_WEBHOOK_SECRET','REVIEWER_EMAILS','GOOGLE_APPLICATION_CREDENTIALS','GOOGLE_DRIVE_FOLDER_ID','GOOGLE_SHEET_ID','RESEND_API_KEY','EMAIL_FROM','WHATSAPP_PHONE_NUMBER_ID','WHATSAPP_ACCESS_TOKEN','META_GRAPH_VERSION','WHATSAPP_OTP_TEMPLATE','WHATSAPP_REGISTRATION_TEMPLATE','WHATSAPP_ACCEPTED_TEMPLATE','WHATSAPP_DECLINED_TEMPLATE'];
export function createApp(env=process.env,adapters={}){
 const live=env.APP_MODE==='live';const missing=required.filter(key=>!env[key]);if(live&&missing.length)throw new Error('Missing backend settings: '+missing.join(', '));if(live&&(env.SESSION_SECRET.length<32||env.REVIEW_WEBHOOK_SECRET.length<32))throw new Error('Use secrets of at least 32 characters.');if(live&&!env.FRONTEND_ORIGIN.startsWith('https://')&&env.NODE_ENV!=='test')throw new Error('The live frontend must use HTTPS.');
 const secret=env.SESSION_SECRET||token();const dataDir=resolve(env.DATA_DIR||'backend/data');mkdirSync(dataDir,{recursive:true,mode:0o700});const db=new DatabaseSync(adapters.database||resolve(dataDir,'identity.sqlite'));db.exec("PRAGMA journal_mode=WAL; CREATE TABLE IF NOT EXISTS sessions(id TEXT PRIMARY KEY, data TEXT NOT NULL, expires INTEGER NOT NULL); CREATE TABLE IF NOT EXISTS applications(reference TEXT PRIMARY KEY, session_id TEXT UNIQUE, data TEXT NOT NULL); CREATE TABLE IF NOT EXISTS jobs(id TEXT PRIMARY KEY, reference TEXT NOT NULL, kind TEXT NOT NULL, attempts INTEGER DEFAULT 0, due INTEGER NOT NULL, state TEXT DEFAULT 'queued'); CREATE TABLE IF NOT EXISTS rate_events(key TEXT NOT NULL, time INTEGER NOT NULL);");
 const store=adapters.store||new GoogleStore(env),messages=adapters.messages||new Messages(env);let processing=false;const passkeys=adapters.passkeys||(()=>import('@simplewebauthn/server'));
 function readSession(id){const row=db.prepare('SELECT * FROM sessions WHERE id=? AND expires>?').get(id,Date.now());if(!row)throw new Problem('Your session expired. Please start again.',401);return JSON.parse(row.data);}
 function saveSession(id,data){db.prepare('UPDATE sessions SET data=? WHERE id=?').run(JSON.stringify(data),id);}
 function appByReference(reference){const row=db.prepare('SELECT data FROM applications WHERE reference=?').get(reference);if(!row)throw new Problem('Application not found.',404);return JSON.parse(row.data);}
 function saveApp(app){db.prepare('UPDATE applications SET data=? WHERE reference=?').run(JSON.stringify(app),app.reference);}
 function rate(key,max,window){const now=Date.now();db.prepare('DELETE FROM rate_events WHERE time<?').run(now-86400000);const count=db.prepare('SELECT count(*) AS n FROM rate_events WHERE key=? AND time>?').get(key,now-window).n;if(count>=max)throw new Problem('Too many requests. Please try again later.',429);db.prepare('INSERT INTO rate_events VALUES(?,?)').run(key,now);}
 function queue(reference,kind){db.prepare('INSERT OR IGNORE INTO jobs(id,reference,kind,due) VALUES(?,?,?,?)').run(reference+':'+kind,reference,kind,Date.now());}
 async function processJobs(){if(processing||!live)return;processing=true;try{for(const job of db.prepare("SELECT * FROM jobs WHERE state='queued' AND due<=? ORDER BY due LIMIT 10").all(Date.now())){let app=appByReference(job.reference);try{if(job.kind==='sheet')await store.update(app);else{const result=await messages[job.kind](app);app[job.kind+'Message']='sent';app[job.kind+'MessageId']=result;saveApp(app);queue(app.reference,'sheet'); // A completed sync must be rerun for subsequent notifications.
 db.prepare("UPDATE jobs SET state='queued',attempts=0,due=? WHERE id=?").run(Date.now(),app.reference+':sheet');}db.prepare("UPDATE jobs SET state='sent' WHERE id=?").run(job.id);}catch{const attempts=job.attempts+1;db.prepare('UPDATE jobs SET attempts=?,state=?,due=? WHERE id=?').run(attempts,attempts>=8?'failed':'queued',Date.now()+Math.min(3600000,30000*2**attempts),job.id);if(job.kind!=='sheet'){app[job.kind+'Message']=attempts>=8?'failed':'queued';saveApp(app);queue(app.reference,'sheet');db.prepare("UPDATE jobs SET state='queued',attempts=0,due=? WHERE id=?").run(Date.now(),app.reference+':sheet');}console.error('Integration job failed:',job.kind,'attempt',attempts);}}}finally{processing=false;}}
 const timer=setInterval(()=>processJobs().catch(()=>console.error('Outbox worker failed.')),15000);timer.unref();
 function json(res,status,body,origin){res.writeHead(status,{'Content-Type':'application/json','Cache-Control':'no-store','X-Content-Type-Options':'nosniff',...(origin?{'Access-Control-Allow-Origin':origin,'Vary':'Origin'}:{})});res.end(JSON.stringify(body));}
 async function body(req){let parts=[],length=0;for await(const chunk of req){length+=chunk.length;if(length>4.5*1024*1024)throw new Problem('Request is too large.',413);parts.push(chunk);}try{return JSON.parse(Buffer.concat(parts).toString()||'{}');}catch{throw new Problem('Invalid JSON.');}}
 const server=http.createServer(async(req,res)=>{const origin=req.headers.origin;const allowedOrigin=origin===env.FRONTEND_ORIGIN?origin:null;try{const path=new URL(req.url,'http://localhost').pathname;
 if(req.method==='OPTIONS'){if(!allowedOrigin)throw new Problem('Origin not permitted.',403);res.writeHead(204,{'Access-Control-Allow-Origin':allowedOrigin,'Access-Control-Allow-Methods':'GET, POST, OPTIONS','Access-Control-Allow-Headers':'Content-Type, Authorization','Vary':'Origin'});return res.end();}
 if(path==='/health')return json(res,200,{ok:true,mode:live?'live':'demo'},allowedOrigin);
 if(!path.startsWith('/api/')){if(req.method!=='GET')throw new Problem('Method not allowed.',405);const file=resolve('public','.'+decodeURIComponent(path==='/'?'/index.html':path));if(!file.startsWith(resolve('public')+'/')||!existsSync(file))throw new Problem('Not found.',404);res.writeHead(200,{'Content-Type':({'.html':'text/html; charset=utf-8','.css':'text/css','.js':'text/javascript','.svg':'image/svg+xml'})[extname(file)]||'application/octet-stream','X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer','Permissions-Policy':'camera=(self), microphone=()','Content-Security-Policy':"default-src 'self'; img-src 'self' data: blob:; media-src 'self' blob:; style-src 'self' 'unsafe-inline'; connect-src 'self' "+(env.FRONTEND_ORIGIN||'')});return res.end(readFileSync(file));}
 if(!live)throw new Problem('Live integrations are not configured. The website is in test mode.',503);
 if(path==='/api/reviews/decision'||path==='/api/reviews/retry'){if(req.method!=='POST')throw new Problem('Method not allowed.',405);const provided=String(req.headers.authorization||'').replace(/^Bearer /,'');if(!compare(provided,env.REVIEW_WEBHOOK_SECRET))throw new Problem('Reviewer authorization required.',401);const data=await body(req);if(path.endsWith('/retry')){const app=appByReference(data.reference);db.prepare("UPDATE jobs SET state='queued',attempts=0,due=? WHERE reference=? AND state='failed'").run(Date.now(),app.reference);return json(res,200,{queued:true});}const reviewers=env.REVIEWER_EMAILS.toLowerCase().split(',').map(x=>x.trim());const reviewer=String(data.reviewedBy||'').toLowerCase();if(!reviewers.includes(reviewer))throw new Problem('Reviewer is not authorized.',403);const app=appByReference(data.reference);const changed=validateDecision(app.status,data.status);if(changed){app.status=data.status;app.reviewedBy=reviewer;app.reviewedAt=new Date().toISOString();if(data.note!==undefined)app.reviewNote=String(data.note).slice(0,1000);app.decisionMessage='queued';db.exec('BEGIN');try{saveApp(app);queue(app.reference,'decision');queue(app.reference,'sheet');db.prepare("UPDATE jobs SET state='queued',attempts=0,due=? WHERE id=?").run(Date.now(),app.reference+':sheet');db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}}return json(res,200,{reference:app.reference,status:app.status,notification:app.decisionMessage});}
 if(!allowedOrigin)throw new Problem('Origin not permitted.',403);if(!['GET','POST'].includes(req.method))throw new Problem('Method not allowed.',405);const ip=env.TRUST_PROXY==='1'?String(req.headers['x-forwarded-for']||req.socket.remoteAddress).split(',')[0]:req.socket.remoteAddress;rate(digest(secret,'request:'+ip),120,60000);
 if(path==='/api/session'&&req.method==='POST'){rate(digest(secret,'session:'+ip),20,3600000);const bearer=token(),id=digest(secret,bearer);db.prepare('INSERT INTO sessions VALUES(?,?,?)').run(id,JSON.stringify({verified:{},challenges:{},createdAt:Date.now()}),Date.now()+86400000);return json(res,201,{token:bearer},allowedOrigin);}
 const bearer=String(req.headers.authorization||'').replace(/^Bearer /,'');if(!bearer)throw new Problem('Start a verification session first.',401);const id=digest(secret,bearer),s=readSession(id);const data=req.method==='POST'?await body(req):{};
 if(path==='/api/otp/send'&&req.method==='POST'){if(s.reference)throw new Problem('This application is already submitted.',409);if(data.consent!==true)throw new Problem('Message consent is required.');const value=validateContact(data.factor,data.value),factor=data.factor;rate(digest(secret,'otp:'+value),5,3600000);if(s.challenges[factor]?.sentAt>Date.now()-60000)throw new Problem('Wait one minute before requesting another code.',429);const otp=code();s.challenges[factor]={value,hash:digest(secret,value+':'+otp),sentAt:Date.now(),expires:Date.now()+600000,attempts:0,used:false};delete s.verified[factor];delete s.passkey;saveSession(id,s);try{await messages.otp(factor,value,otp);}catch{delete s.challenges[factor];saveSession(id,s);throw new Problem('The verification message could not be sent. Please try again.',502);}return json(res,200,{sent:true},allowedOrigin);}
 if(path==='/api/otp/verify'&&req.method==='POST'){const value=validateContact(data.factor,data.value);try{s.verified[data.factor]=verifyChallenge(s.challenges[data.factor],{value,code:String(data.code||'')},secret);}finally{saveSession(id,s);}return json(res,200,{verified:true},allowedOrigin);}
 if(path==='/api/passkey/options'&&req.method==='POST'){if(!s.verified.email||!s.verified.whatsapp)throw new Problem('Verify both contacts first.',403);if(s.reference)throw new Problem('This application is already submitted.',409);const auth=await passkeys();s.userHandle||=token();const options=await auth.generateRegistrationOptions({rpName:'New Tibet',rpID:env.RP_ID,userID:Buffer.from(s.userHandle,'base64url'),userName:s.verified.email,attestationType:'none',authenticatorSelection:{residentKey:'required',userVerification:'required'},supportedAlgorithmIDs:[-7,-257],extensions:{prf:{}}});s.passkeyChallenge={value:options.challenge,expires:Date.now()+300000};saveSession(id,s);return json(res,200,options,allowedOrigin);}
 if(path==='/api/passkey/verify'&&req.method==='POST'){if(!s.passkeyChallenge||s.passkeyChallenge.expires<Date.now())throw new Problem('Passkey challenge expired. Try again.');const challenge=s.passkeyChallenge.value;delete s.passkeyChallenge;saveSession(id,s);const auth=await passkeys();let result;try{result=await auth.verifyRegistrationResponse({response:data.credential,expectedChallenge:challenge,expectedOrigin:env.FRONTEND_ORIGIN,expectedRPID:env.RP_ID,requireUserVerification:true});}catch{throw new Problem('Passkey verification failed. Please try again.');}if(!result.verified||!result.registrationInfo)throw new Problem('Passkey verification failed.');const cred=result.registrationInfo.credential;s.passkey={id:cred.id,publicKey:Buffer.from(cred.publicKey).toString('base64url'),counter:cred.counter,transports:cred.transports||[],prfSupported:Boolean(data.credential.clientExtensionResults?.prf?.enabled),userHandle:s.userHandle};saveSession(id,s);return json(res,200,{verified:true},allowedOrigin);}
 if(path==='/api/applications'&&req.method==='POST'){const existing=db.prepare('SELECT data FROM applications WHERE session_id=?').get(id);if(existing){const app=JSON.parse(existing.data);return json(res,200,{reference:app.reference,status:app.status,notification:app.registrationMessage},allowedOrigin);}if(s.submitting&&s.submittingAt>Date.now()-120000)throw new Problem('Your submission is already being processed.',409);const validated=validateApplication(data,s);s.submitting=true;s.submittingAt=Date.now();s.submissionReference||='NT-'+randomUUID().toUpperCase();saveSession(id,s);let uploaded;try{const reference=s.submissionReference;uploaded=await store.photo(reference,validated.photo);const {photo,...fields}=validated;const app={...fields,reference,createdAt:new Date().toISOString(),status:'pending',photoURL:uploaded.url,photoId:uploaded.id,passkey:s.passkey||null,registrationMessage:'queued'};await store.append(app);db.exec('BEGIN');try{db.prepare('INSERT INTO applications VALUES(?,?,?)').run(reference,id,JSON.stringify(app));queue(reference,'registration');s.reference=reference;s.submitting=false;saveSession(id,s);db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}return json(res,201,{reference,status:'pending',notification:'queued'},allowedOrigin);}catch(e){s.submitting=false;saveSession(id,s);// Keep any private upload for an idempotent retry with the same reference.
throw new Problem('Your application could not be stored. Please try again.',502);}}
 if(path==='/api/applications/status'&&req.method==='GET'){if(!s.reference)throw new Problem('No application in this session.',404);const app=appByReference(s.reference);return json(res,200,{reference:app.reference,status:app.status},allowedOrigin);}
 throw new Problem('Endpoint not found.',404);
 }catch(e){if(!(e instanceof Problem))console.error('Request failed:',e.name);json(res,e.status||500,{error:e instanceof Problem?e.message:'The service is temporarily unavailable. Please try again.'},allowedOrigin);}});
 server.on('close',()=>{clearInterval(timer);db.close();});return {server,db,processJobs};
}
if(process.argv[1]&&import.meta.url===pathToFileURL(resolve(process.argv[1])).href){const {server}=createApp();server.listen(Number(process.env.PORT||4173),'0.0.0.0',()=>console.log('New Tibet server listening on port '+(process.env.PORT||4173)));}
