import test from 'node:test';import assert from 'node:assert/strict';
import {validateContact,verifyChallenge,digest,validateApplication,validateDecision,spreadsheetText,validateMedia} from '../backend/core.mjs';
const secret='test-secret';
test('contacts normalize but require valid email and international WhatsApp number',()=>{assert.equal(validateContact('email',' TEST@example.org '),'test@example.org');assert.equal(validateContact('whatsapp','+91 98765 43210'),'+919876543210');assert.throws(()=>validateContact('whatsapp','9876543210'));assert.throws(()=>validateContact('sms','+919876543210'));});
test('OTP binds to recipient, expires, limits guesses and cannot be reused',()=>{const c={value:'test@example.org',hash:digest(secret,'test@example.org:123456'),expires:2000,attempts:0};assert.throws(()=>verifyChallenge(c,{value:'other@example.org',code:'123456'},secret,1000));assert.equal(verifyChallenge(c,{value:c.value,code:'123456'},secret,1000),c.value);assert.throws(()=>verifyChallenge(c,{value:c.value,code:'123456'},secret,1000));assert.throws(()=>verifyChallenge({...c,used:false,expires:900},{value:c.value,code:'123456'},secret,1000));assert.throws(()=>verifyChallenge({...c,used:false,attempts:5},{value:c.value,code:'123456'},secret,1000));});
test('submission requires consent, verified contacts, all media, matching book, with passport NFC optional',()=>{const body={name:'Test Person',email:'test@example.org',whatsapp:'+919876543210',book:'green',consent:true,consentVersion:'2026-10-07'};const session={verified:{email:body.email,whatsapp:body.whatsapp},mediaChallenge:{expires:Date.now()+60000},media:Object.fromEntries(['front','back','identity','challenge','video'].map(k=>[k,{book:'green'}])),passport:{verified:true,expires:Date.now()+60000}};assert.equal(validateApplication(body,session).book,'green');assert.throws(()=>validateApplication({...body,email:'attacker@example.org'},session));assert.throws(()=>validateApplication({...body,consent:false},session));assert.throws(()=>validateApplication({...body,book:'blue'},session));for(const kind of Object.keys(session.media)){const media={...session.media};delete media[kind];assert.throws(()=>validateApplication(body,{...session,media}));}assert.equal(validateApplication(body,{...session,passport:null}).book,'green');assert.equal(validateApplication(body,{...session,passport:{verified:true,expires:0}}).book,'green');});
test('media rejects unsupported, oversized, or invalid envelopes',()=>{const jpeg=Buffer.concat([Buffer.from([255,216]),Buffer.alloc(200),Buffer.from([255,217])]);assert.equal(validateMedia('front','image/jpeg',jpeg),'image/jpeg');assert.throws(()=>validateMedia('back','image/png',jpeg));assert.throws(()=>validateMedia('challenge','image/jpeg',Buffer.alloc(200)));assert.throws(()=>validateMedia('video','video/webm',jpeg));assert.throws(()=>validateMedia('video','video/mp4',Buffer.alloc(21*1024*1024)));const webm=Buffer.concat([Buffer.from([0x1a,0x45,0xdf,0xa3]),Buffer.alloc(200)]);assert.equal(validateMedia('video','video/webm',webm),'video/webm');});
test('manual decisions are idempotent and final',()=>{assert.equal(validateDecision('pending','accepted'),true);assert.equal(validateDecision('accepted','accepted'),false);assert.throws(()=>validateDecision('accepted','declined'));assert.throws(()=>validateDecision('pending','approved'));});
test('reviewer text cannot introduce spreadsheet formulas',()=>{assert.equal(spreadsheetText('=HYPERLINK("bad")'),'\'=HYPERLINK("bad")');assert.equal(spreadsheetText('Test Person'),'Test Person');});
